### ISSUE TITLE
Несоответствие по объему между Квиком и Сайтом после продажи

### ISSUE THREAD

**Issue by Vladislav140876** [demen777/assets#10]
Добрый день.

Сейчас продаются облигации, и текущий объем на сайте на единицу больше чем в квике. Непривязанных транзакций нет. Прошу исправить, если исправить не получится сделаю ручной импорт.
![image](https://user-images.githubusercontent.com/64786514/81046928-cd7cb580-8ed2-11ea-9688-4490870bce87.png)

**Comment by demen777** [comment]
Напиши id сделок из quik которые по 1 объему были

**Comment by Vladislav140876** [comment]
Идентификаторы это первое поле в строке
3180017745,20233624447,10:57:59,S,66762/,MU009460071A,,L01-00000F00,TQTD,FXTB,10.1940,1,10.19,07.05.2020,,,N,0.0000,Y2,T,,0.02,0.0000,,,,0,,,,N,0.01,0.01,0.00,66762,00696,,N,USD,,05.05.2020
3180019230,20233624447,10:58:56,S,66762/,MU009460071A,,L01-00000F00,TQTD,FXTB,10.1940,1,10.19,07.05.2020,,,N,0.0000,Y2,T,,0.02,0.0000,,,,0,,,,N,0.01,0.01,0.00,66762,00696,,N,USD,,05.05.2020

**Comment by demen777** [comment]
Проблема в транзакции tradeNum = 3180019230, он у меня идет как покупка, а у тебя как продажа. На tradeNum настроена фильтрация событий-дубликатов + tradeNum используется как id  в таблице quik_trade. 
Необходимо будет в фильтрацию добавить например client_code.
В QuikTrade необходимо будет добавить синтетический ключ

Для исправления проблемы (так как событие было отфильтровано и не сохранилось) импортируй файл:
Symbol,Trade Date,Purchase Price,Quantity
FXTB.ME,20200505,10.1940,-1

**Comment by demen777** [comment]
Развернута версия 0.5.2 которая должна решить проблему обработки двух транзакций с одинаковым tradeNum

**Comment by Vladislav140876** [comment]
Применил, спасибо!
