### ISSUE TITLE
МТС разные объемы на сайте и квике

### ISSUE THREAD

**Issue by Vladislav140876** [demen777/assets#11]
Добрый день!

В портфеле "Акции RU" было 180 акций МТС, затем были продажи и покупки по списку (см. скриншот). В итоге на сайте баланс по МТС 0, а на сайте баланс -150. Прошу исправить и/или предложить коррекцию импортом файла

![image](https://user-images.githubusercontent.com/64786514/81172131-1c9c1680-8fb7-11ea-9e4c-d58ee7de819e.png)

**Comment by demen777** [comment]
Из адаптера все сделки пришли верно (таблица quik_trade), 
но далее в таблице (transaction) - сделки с объемами -20 и -310 задублировались - разбираюсь почему.

**Comment by demen777** [comment]
Вероятно это произошло из-за того что tryLink производящий связывание Transaction с активом у меня выполняется в БД транзакции отдельной от БД транзакции в которой происходит создание транзакции и получилось так, что при save Transaction после связывания, ее "оригинал" еще не был закоммитчен и была создана запись дубль. Непонятно почему всегда так не происходит. Видимо уберу использование новой транзакции. 

Как исправлять - подумаю.
Ты вручную потом эти записи связывал?

**Comment by demen777** [comment]
А всегда это не происходило потому что обработка Quik_trade происходит в отдельном потоке и видимо транзакция которую он захватывал обычно завершается позднее чем он завершался и коммитил. Надо как-то более прозрачно сделать

**Comment by Vladislav140876** [comment]
Да, я многие связал вручную.

**Comment by demen777** [comment]
Установил версию 0.5.3 - в ней вручную сохраняю в отдельных транзакциях QuikTrade и Transaction, а затем делаю их attach (с помощью findById) в текущую транзакцию.
По идее если бумага продана не в шорт, а для закрытия существующей позиции - должна произойти автолинковка, поэтому при наличии продаж в непривязанных транзакциях лучше запостить баг.
С 2 дублями по МТС буду разбираться.

**Comment by demen777** [comment]
Пофиксил отрицательный актив по МТС.
