### ISSUE TITLE
Выводить отдельно суммы в долларах и в рублях

### ISSUE THREAD

**Issue by Vladislav140876** [demen777/assets#16]
Добрый день.

А можно сделать вывод отдельно в долларах, отдельно в рублях данные? Например так:
Рубли;ЛиквиднаяСтоимость;ВКэше;Всего
Доллары;ЛиквиднаяСтоимость;ВКэше;Всего

**Comment by demen777** [comment]
Это про раздел "Активы на бирже" ?
Для чего такое разделение?

**Comment by Vladislav140876** [comment]
Да, я думаю в "Активы на бирже".
Ну допустим есть цель держать на счете 25 тыс долларов. И чтобы это контролировать, а также смотреть прогресс (увеличивается/уменьшается) нужно сейчас суммировать суммы по долларовым портфелям, потом идти к Квик и там брать кэши в долларах (с нескольких счетов еще :( ).

**Comment by Vladislav140876** [comment]
Можно было бы смотреть прогресс по "Активы на бирже" по полю "Всего в RUB", но там курс доллара еще влияет на эту сумму, и чисто долларовый прогресс не отследить.

**Comment by demen777** [comment]
Вижу два варианта решения:
1. Сделать как ты предлагаешь + добавить типа Итого       
              Кэш | В портфелях | Всего
RUB
USD
Итого

2. Вариант - если тебя именно доллары интересуют - то сделать настройку на уровне пользователя в какой валюте ему отображать суммарную информацию

**Comment by demen777** [comment]
Да, для первого вариант все равно надо будет валюту задавать в какой Итого выводить

**Comment by Vladislav140876** [comment]
Я думаю вариант 1.
Вариант 2 решения вопроса не даст, т.к. (а) появится зеркальная потребность по оценке рублевого "всего", и (б) изменяющийся курс тоже будет оказывать влияние.

По валюте "Итого" устроил бы текущий вариант в рублях.

**Comment by Vladislav140876** [comment]
Не знаю, если форма будет расползаться по размеру, то наверное можно от "Активы на бирже" сделать ссылку на новую форму где раскрыть детали по валютам.

**Comment by demen777** [comment]
Ну ок тогда идем по 1-варианту с отображением Итогов в рублях. Думаю сильно не расползется. Единственное - сейчас рефакторинг большой идет который почти все ломает и новые фичи только после него будут.

**Comment by demen777** [comment]
Реализовано в версии 0.7.0.
Необходимо вероятно фильтровать строки по валютам со всеми нулями. У меня такая валюта сейчас EUR.

**Comment by Vladislav140876** [comment]
Ага, спасибо.
Фильтровать EUR можно . На уровне глобальной настройки я думаю.

**Comment by demen777** [comment]
Нет настройки я тут городить не буду - просто если в кэше и портфелях валюта = 0 то строка будет отфильтрована

**Comment by Vladislav140876** [comment]
Ааа, ок.

**Comment by demen777** [comment]
Отфильтровал нулевую строку
