### ISSUE TITLE
Не импортировались сделки

### ISSUE THREAD

**Issue by Vladislav140876** [demen777/assets#17]
Привет!

Были такие сделки. Хотел купить одну, но по ошибке продал одну, а потом для компенсации докупил две. Сейчас у меня по сумме на трех счетах 5 таких бумаг. А на сайте показывается четыре.

![image](https://user-images.githubusercontent.com/64786514/82791680-a2f59b00-9e87-11ea-9fb0-63ea72f7120c.png)

Посмотри плиз.

**Comment by demen777** [comment]
Привет.

Видимо были проблемы с сетью как минимум у моего сервера в это время. Надо обе сделки импортировать вручную.

May 22 19:40:35 dmserver autossh[646]: ssh: Could not resolve hostname robothome.ddns.net: Temporary failure in name resolution
May 22 19:44:41 dmserver ddclient[766]: WARNING:  cannot connect to checkip.dyndns.com:80 socket: IO::Socket::INET: Bad hostname 'checkip.dyndns.com'
May 22 19:50:21 dmserver ddclient[766]: WARNING:  cannot connect to checkip.dyndns.com:80 socket: IO::Socket::INET: Bad hostname 'checkip.dyndns.com'
May 22 19:51:15 dmserver autossh[646]: ssh: Could not resolve hostname robothome.ddns.net: Temporary failure in name resolution

**Comment by Vladislav140876** [comment]
Ок, импортирую.
