### ISSUE TITLE
Не открывается портфель

### ISSUE THREAD

**Issue by Vladislav140876** [demen777/assets#18]
Привет. Есть ошибка в работе сайта.
а) Купил облигаций 
![image](https://user-images.githubusercontent.com/64786514/83018595-0675f900-a03f-11ea-878e-4a90f4653b12.png)
б) Забиндил в портфель "Облигации RU"

Теперь этот портфель не открывается с ошибкой
![image](https://user-images.githubusercontent.com/64786514/83018552-f100cf00-a03e-11ea-9266-3d56802d0be6.png)

**Comment by Vladislav140876** [comment]
У меня проскользнула мысль что если автобинд не произошел, то руками не биндить. Но я подумал что это правило к продажам относится.

**Comment by demen777** [comment]
Нет это баг. Лучше пока не биндить покупки.

**Comment by demen777** [comment]
Сделал обновление, посмотри стал портфель отображаться

**Comment by Vladislav140876** [comment]
Ок, отображается. Но неправильно считается. Должно быть в сумме 1227 тыс, а на главной странице показывает 1313 тыс.

![image](https://user-images.githubusercontent.com/64786514/83023897-f82bdb00-a046-11ea-95ce-143673e7c362.png)

**Comment by demen777** [comment]
Вроде пофиксил

**Comment by Vladislav140876** [comment]
Ага, нормально! Спасибо.
